//! Build-time generator for the GFM spec tests. Zig can't declare tests in a
//! loop, so this reads `spec.txt` and writes a Zig file with one test per
//! example per `Mutation`, each calling `spec_check.checkCase`. A pair listed
//! in `known_failures.zig` instead calls `spec_check.expectKnownFailure` and
//! then returns `error.SkipZigTest`, so it's reported as skipped.
//!
//! Usage: gen_spec_tests <spec.txt> <output.zig>

const std = @import("std");
const gfm_spec = @import("gfm_spec.zig");
const known_failures = @import("known_failures.zig");

/// The number of examples found in spec.txt must exceed this, or generation
/// fails. Guards against the parser silently matching nothing, e.g. if the
/// fence format changes. The pinned spec has 670 examples that aren't
/// disabled.
const min_examples = 600;

pub fn main(init: std.process.Init) !u8 {
    const io = init.io;
    const arena = init.arena.allocator();

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        std.debug.print("usage: {s} <spec.txt> <output.zig>\n", .{args[0]});
        return 2;
    }

    const cwd = std.Io.Dir.cwd();
    const spec = try cwd.readFileAlloc(io, args[1], arena, .unlimited);

    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    try w.writeAll(
        \\//! Generated by test/gen_spec_tests.zig from cmark-gfm's test/spec.txt.
        \\//! Do not edit.
        \\
        \\const spec_check = @import("spec_check");
        \\
        \\const examples = [_]spec_check.Example{
        \\
    );
    var examples: std.ArrayListUnmanaged(gfm_spec.Example) = .empty;
    var it = gfm_spec.ExampleIterator.init(arena, spec);
    while (try it.next()) |example| {
        // The spec marks these as not passing in cmark-gfm itself.
        if (std.mem.eql(u8, example.extension, "disabled")) continue;
        try examples.append(arena, example);
        try w.print(
            "    .{{ .number = {d}, .section = \"{f}\", .extension = \"{f}\", .markdown = \"{f}\" }},\n",
            .{ example.number, std.zig.fmtString(example.section), std.zig.fmtString(example.extension), std.zig.fmtString(example.markdown) },
        );
    }
    try w.writeAll("};\n");
    if (examples.items.len <= min_examples) {
        std.debug.print("only {d} example(s) found in {s}; expected more than {d}\n", .{ examples.items.len, args[1], min_examples });
        return 1;
    }

    // Which known failures matched a generated test, so a stale or mistyped
    // entry (e.g. for a disabled example) can't go unnoticed. Allocated
    // rather than an array, which couldn't be indexed if there are none.
    const matched = try arena.alloc(bool, known_failures.entries.len);
    @memset(matched, false);
    for (examples.items, 0..) |example, i| {
        for (std.enums.values(gfm_spec.Mutation)) |mutation| {
            try w.print("\ntest \"GFM spec example {d} ({f}): {t}\" {{\n", .{ example.number, std.zig.fmtString(example.section), mutation });
            if (known_failures.lookup(example.number, mutation)) |found| {
                matched[found.index] = true;
                try w.print(
                    "    // Known failure; see `{t}` in test/known_failures.zig.\n    try spec_check.expectKnownFailure(examples[{d}], .{t}, .{t});\n    return error.SkipZigTest;\n",
                    .{ found.reason, i, mutation, found.reason },
                );
            } else {
                try w.print("    try spec_check.checkCase(examples[{d}], .{t});\n", .{ i, mutation });
            }
            try w.writeAll("}\n");
        }
    }
    var unmatched = false;
    for (known_failures.entries, matched) |entry, ok| {
        if (ok) continue;
        std.debug.print("known failure for example {d} ({t}) matches no generated test\n", .{ entry.number, entry.mutation });
        unmatched = true;
    }
    if (unmatched) return 1;

    try cwd.writeFile(io, .{ .sub_path = args[2], .data = out.written() });
    return 0;
}
