//! Property checks run over every example in the GFM spec (`test/spec.txt`).
//! The tests themselves are generated by `gen_spec_tests.zig`, one per example per mutation.
//! Each calls `checkCase`, or `expectKnownFailure` if the pair is listed in `known_failures.zig`.
//! The spec's expected HTML is not used.
//! Tool rewrites Markdown source, so instead each example is fixed and checked for properties that must hold for any input.
//!
//! - Idempotence: fixing already-fixed output changes nothing.
//! - Semantics preserved: the fixed source renders to the same HTML as the original,
//!   treating a soft line break the same as a space.
//!
//! Few of the spec examples have two clauses on one line.
//! To get better coverage, each example is also run through mutations (see `Mutation`) that add clause boundaries next to every construct the spec covers.
//! The properties hold for any input, so a mutated example needs no expected output of its own.

const std = @import("std");
const markz = @import("markz");
const reflow = @import("reflow");
const gfm_spec = @import("gfm_spec.zig");
const FailureReason = @import("known_failures.zig").FailureReason;

pub const Example = gfm_spec.Example;
const Mutation = gfm_spec.Mutation;

/// Every example and mutation is checked under each of these.
const escape_modes = [_]reflow.Options{ .{ .escape = true }, .{ .escape = false } };

fn fix(arena: std.mem.Allocator, source: []const u8, options: reflow.Options) ![]u8 {
    var doc = try markz.parseWith(arena, source, .{ .gfm = true });
    const result = try reflow.analyze(arena, &doc, options);
    return reflow.applyInsertions(arena, source, result.insertions);
}

/// Render to HTML with every run of spaces, tabs, and newlines (all HTML
/// whitespace) collapsed to a single space, so a clause moved onto its own
/// line compares equal.
fn renderNormalized(arena: std.mem.Allocator, source: []const u8) ![]u8 {
    var doc = try markz.parseWith(arena, source, .{ .gfm = true });
    const html = try markz.renderHtml(arena, &doc);
    var out: std.ArrayListUnmanaged(u8) = .empty;
    var in_space = false;
    for (html) |c| {
        if (c == ' ' or c == '\t' or c == '\n') {
            if (!in_space) try out.append(arena, ' ');
            in_space = true;
        } else {
            try out.append(arena, c);
            in_space = false;
        }
    }
    return out.items;
}

/// Apply `mutation` to every non-blank line of `markdown`.
fn mutate(arena: std.mem.Allocator, markdown: []const u8, mutation: Mutation) ![]const u8 {
    if (mutation == .none) return markdown;
    var out: std.ArrayListUnmanaged(u8) = .empty;
    var lines = std.mem.splitScalar(u8, markdown, '\n');
    var first = true;
    while (lines.next()) |line| {
        if (!first) try out.append(arena, '\n');
        first = false;
        if (std.mem.trim(u8, line, " \t").len == 0) {
            try out.appendSlice(arena, line);
            continue;
        }
        switch (mutation) {
            .none => unreachable,
            .prefix_lines => {
                try out.appendSlice(arena, "Lead clause. ");
                try out.appendSlice(arena, line);
            },
            .suffix_lines => {
                try out.appendSlice(arena, line);
                try out.appendSlice(arena, " Tail clause.");
            },
            .insert_boundary => {
                const at = for (1..@max(line.len, 2) - 1) |i| {
                    if (line[i] == ' ' and std.ascii.isAlphanumeric(line[i - 1]) and std.ascii.isAlphanumeric(line[i + 1])) break i;
                } else null;
                if (at) |i| {
                    try out.appendSlice(arena, line[0..i]);
                    try out.appendSlice(arena, ". Next ");
                    try out.appendSlice(arena, line[i + 1 ..]);
                } else {
                    try out.appendSlice(arena, line);
                }
            },
        }
    }
    return out.items;
}

/// Returns a description of the first property `markdown` violates when
/// fixed with `options`, or null.
fn check(arena: std.mem.Allocator, markdown: []const u8, options: reflow.Options) !?[]const u8 {
    const fixed = try fix(arena, markdown, options);
    const refixed = try fix(arena, fixed, options);
    if (!std.mem.eql(u8, fixed, refixed)) {
        return try std.fmt.allocPrint(arena, "not idempotent\n--- fixed ---\n{s}--- fixed again ---\n{s}", .{ fixed, refixed });
    }
    const before = try renderNormalized(arena, markdown);
    const after = try renderNormalized(arena, fixed);
    if (!std.mem.eql(u8, before, after)) {
        return try std.fmt.allocPrint(arena, "rendering changed\n--- fixed ---\n{s}--- html before ---\n{s}\n--- html after ---\n{s}\n", .{ fixed, before, after });
    }
    return null;
}

/// Check `example` under `mutation`, in each of `escape_modes`, and fail if
/// any property is violated.
pub fn checkCase(example: Example, mutation: Mutation) !void {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const markdown = try mutate(arena, example.markdown, mutation);
    var failed = false;
    for (escape_modes) |options| {
        const msg = try check(arena, markdown, options) orelse continue;
        failed = true;
        std.debug.print("\n=== escape {}: {s}\n--- markdown ---\n{s}", .{ options.escape, msg, markdown });
    }
    if (failed) return error.TestUnexpectedResult;
}

/// Check that `example` under `mutation`, listed in `known_failures.zig`
/// for `reason`, still violates a property in each of `escape_modes`. Fails
/// if it passes in any of them, so a fixed entry gets removed from the
/// list. The generated test reports itself as skipped after this returns.
pub fn expectKnownFailure(example: Example, mutation: Mutation, reason: FailureReason) !void {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const markdown = try mutate(arena, example.markdown, mutation);
    var passed = false;
    for (escape_modes) |options| {
        if (try check(arena, markdown, options) != null) continue;
        passed = true;
        std.debug.print("\n=== escape {}: listed in known_failures.zig ({t}) but now passes; remove it\n", .{ options.escape, reason });
    }
    if (passed) return error.TestUnexpectedResult;
}
